# Generated by Django 4.1.9 on 2023-07-06 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chore",
            name="assignees",
        ),
    ]
